# Development Configuration


# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:900000}



# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${spring.mail.username}


# Frontend
app.frontend.url=http://localhost:5173



# Audit Engine
audit.engine.url=${AUDIT_ENGINE_URL:http://localhost:3001}
audit.engine.api-key=${AUDIT_ENGINE_API_KEY}


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.health.mail.enabled=false